Fusion of buildpack-multi with overlay
Summary:

Since the kickoff of the heroku app of the intel team needed to use custom buildpacks, a fusion of the buildpack-multi and overlay was needed.
The strong point is that any other team who needs custom buildpacks can migrate to this buildpack using the instrucions on the README

Test Plan:

 - running ./bin/detect must always echo a simple string with exit 0
 - running "./bin/compile ." (local) will exit with error if the local environment $OVERLAY is not set.
 - running "./bin/compile ." (local) will exit with error if there is no .buildpacks or .buildpacks.$OVERLAY file
 - set overlay to baz (export OVERLAY=baz), touch foo.bar.baz, and create a .buildpacks. (echo https://github.com/heroku/heroku-buildpack-python > .buildpacks) then run "./bin/compile .". foo.bar.baz must be overlay to foo.bar and it must start downloading the buildpack

CCs:

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 
-set -e
+BUILD_DIR=$1
+
+shopt -s nullglob  # if files don't exist, expand globs to zero arguments instead to themselves
 
 function indent() {
   c='s/^/       /'
@@ -10,9 +12,30 @@ function indent() {
   esac
 }
 
+if [ -z "$OVERLAY" ]; then
+  echo "'OVERLAY' environment variable not set, aborting..."
+  exit 1
+elif [ ! -f $1/.buildpacks ] && [ ! -f $1/.buildpacks.$OVERLAY ]; then
+  echo "no .buildpacks neither .buildpacks.overlay-string file"
+  exit 1
+fi
+
+echo "-----> Overlaying '*.$OVERLAY' over repository root"
+
+cd $BUILD_DIR
+
+for from in *.$OVERLAY .*.$OVERLAY bin/*.$OVERLAY; do
+  to=${from/%.$OVERLAY/}
+  echo "copying '$from' to '$to'" | indent
+  cp $from $to
+done
+
+shopt -u nullglob  # going back to the default behavior, for easiness of detecting simple errors.
+set -e
+
 unset GIT_DIR
 
-for BUILDPACK in $(cat $1/.buildpacks); do
+for BUILDPACK in $(cat $BUILD_DIR/.buildpacks); do
   dir=$(mktemp -t buildpackXXXXX)
   rm -rf $dir
 
@@ -53,4 +76,4 @@ for BUILDPACK in $(cat $1/.buildpacks); do
 done
 
 echo "Using release configuration from last framework $framework:" | indent
-cat $1/last_pack_release.out | indent
+cat $BUILD_DIR/last_pack_release.out | indent
